services:
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    env_file: 
      - ../../.env
    container_name: server_container
    ports:
      - "3000:3000"

    volumes:
      - ../../apps/api:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock

    command: npm run start:dev

  analyzer-agent:
    build:
      context: ../../apps/agents
      dockerfile: Dockerfile
    image: analyzer-agent:latest
    entrypoint: ["echo", "Agent image build complete"]
